# Generated by Django 3.2.2 on 2022-08-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation_and_Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CTC', models.CharField(blank=True, max_length=100, null=True)),
                ('Car_Scheme', models.BooleanField(blank=True, default=False, null=True)),
                ('LTBP', models.BooleanField(blank=True, default=False, null=True)),
                ('Bonus_or_Incentive', models.TextField(blank=True, null=True)),
                ('PF', models.CharField(blank=True, max_length=100, null=True)),
                ('ESIC', models.CharField(blank=True, max_length=100, null=True)),
                ('Gratuity', models.CharField(blank=True, max_length=100, null=True)),
                ('Mediclaim', models.CharField(blank=True, max_length=100, null=True)),
                ('GTL', models.CharField(blank=True, max_length=100, null=True)),
                ('GPA', models.CharField(blank=True, max_length=100, null=True)),
                ('Meal', models.CharField(blank=True, max_length=100, null=True)),
                ('Pass', models.CharField(blank=True, max_length=100, null=True)),
                ('Garden_Leave', models.CharField(blank=True, max_length=100, null=True)),
                ('Leave_General', models.CharField(blank=True, max_length=100, null=True)),
                ('Maternity_or_Paternity', models.CharField(blank=True, max_length=100, null=True)),
                ('Sabbatical_Leave', models.CharField(blank=True, max_length=100, null=True)),
                ('Extended_Sick_Leave', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCN_Disciplinary_Action', models.TextField(blank=True, null=True)),
                ('Warning_or_Caution', models.TextField(blank=True, null=True)),
                ('Other_action', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source_of_Hire', models.CharField(choices=[('Agency', 'Agency'), ('Reference', 'Reference'), ('Portal', 'Portal')], default='Agency', max_length=100)),
                ('Name_of_Agency', models.CharField(blank=True, max_length=100, null=True)),
                ('Name_of_Referral_Emp', models.CharField(blank=True, max_length=100, null=True)),
                ('Full_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Grade', models.CharField(blank=True, max_length=100, null=True)),
                ('Employee_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('Main_Sub_Department_Mapping', models.CharField(blank=True, max_length=100, null=True)),
                ('Job', models.TextField(blank=True, null=True)),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Appraiser_Ecode', models.CharField(blank=True, max_length=100, null=True)),
                ('Appraiser_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('DOJ', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_of_Birth', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Email_Address', models.EmailField(blank=True, max_length=254, null=True)),
                ('Gender', models.CharField(blank=True, max_length=100, null=True)),
                ('KLI_RHRM', models.CharField(blank=True, max_length=100, null=True)),
                ('Confirmation_Date', models.DateField(blank=True, null=True)),
                ('Town_Or_City', models.CharField(blank=True, max_length=100, null=True)),
                ('Notice_Period', models.CharField(blank=True, max_length=100, null=True)),
                ('Served', models.BooleanField(blank=True, default=False, null=True)),
                ('System_LWD', models.CharField(blank=True, max_length=100, null=True)),
                ('DOJ_Group', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(choices=[('(Active)', 'Active'), ('Exit', 'Exit'), ('Absconding', 'Absconding')], default='Active', max_length=100)),
                ('Last_attendance_marked', models.CharField(blank=True, max_length=100, null=True)),
                ('BGV_Status', models.CharField(blank=True, max_length=100, null=True)),
                ('Laptop_or_Desktop', models.CharField(blank=True, max_length=100, null=True)),
                ('Data_card', models.CharField(blank=True, max_length=100, null=True)),
                ('Any_other_IT_gadget', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HR_Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Confirmation_Letter', models.TextField(blank=True, null=True)),
                ('PMS_Letter', models.TextField(blank=True, null=True)),
                ('Any_Other_Letter', models.TextField(blank=True, null=True)),
                ('Recognition', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Training_done', models.BooleanField(blank=True, default=False, null=True)),
                ('Training_done_Date', models.DateField(blank=True, null=True)),
                ('Training_in_Calendar', models.BooleanField(blank=True, default=False, null=True)),
                ('Training_in_Calendar_Date', models.DateField(blank=True, null=True)),
                ('Any_Training_Requirement', models.TextField(blank=True, null=True)),
                ('Employee_Raised_or_Employer_Raised', models.CharField(choices=[('Employee Raised', 'Employee Raised'), ('Employer Raised', 'Employer Raised')], default='Employee Raised', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Onboarding_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education_Certificate', models.TextField(blank=True, null=True)),
                ('Relieving_Letter', models.TextField(blank=True, null=True)),
                ('Joining_Form', models.TextField(blank=True, null=True)),
                ('Adhaar', models.TextField(blank=True, null=True)),
                ('PAN', models.TextField(blank=True, null=True)),
                ('Any_Other_document', models.TextField(blank=True, null=True)),
                ('CIBIL_rating', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PMS_rating_FY_21', models.CharField(blank=True, max_length=100, null=True)),
                ('PMS_rating_FY_20', models.CharField(blank=True, max_length=100, null=True)),
                ('PMS_rating_FY_19', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
