# Generated by Django 3.2.2 on 2022-08-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation_and_benefit',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='life.employee'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='life.employee'),
        ),
        migrations.AddField(
            model_name='hr_letter',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='life.employee'),
        ),
        migrations.AddField(
            model_name='ld',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='life.employee'),
        ),
        migrations.AddField(
            model_name='onboarding_documents',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='life.employee'),
        ),
        migrations.AddField(
            model_name='rating',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='life.employee'),
        ),
    ]
