# Generated by Django 3.2.2 on 2022-08-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_auto_20220810_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compensation_and_benefit',
            old_name='Meal',
            new_name='Meal_Pass',
        ),
        migrations.RemoveField(
            model_name='compensation_and_benefit',
            name='Pass',
        ),
    ]
